//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFMS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PintingFactoryDBEntities : DbContext
    {
        public PintingFactoryDBEntities()
            : base("name=PintingFactoryDBEntities")
        {
        }

        //public PintingFactoryDBEntities(string connectionString) : base(connectionString)
        //{

        //}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmpPosition> EmpPositions { get; set; }
        public virtual DbSet<MachinesForRepair> MachinesForRepairs { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<PrintingMachine> PrintingMachines { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductsToMachine> ProductsToMachines { get; set; }
        public virtual DbSet<TypesOfMachine> TypesOfMachines { get; set; }
    }
}
